name: Build node_modules

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Zip node_modules
        run: zip -r node_modules.zip node_modules

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules.zip
